---
- name: Configure Compute Nodes
  hosts: "*compute*"
  gather_facts: no
  tasks:
  - name: install packages
    become: true
    become_user: root
    dnf:
      state: present
      name:
       - ohpc-base-compute
       - ohpc-slurm-client
       - lmod-ohpc
  - name: Restart slurmd
    ansible.builtin.systemd:
      name: slurmd.service
      enabled: yes
      state: restarted
