---
- name: Configure Login Node
  hosts: "*login*"
  gather_facts: no
  tasks:
  - name: Set innodb.cnf file
    become: true
    blockinfile:
      content: "{{ lookup('template', 'innodb.cnf.j2') }}"
      dest: /etc/my.cnf.d/innodb.cnf
      create: yes  
  - name: Set slurmdb.conf file
    become: true
    template:
      src: slurmdb.conf.j2
      dest: /etc/slurm/slurmdbd.conf
      owner: slurm
      group: slurm
      mode: 0600 
  - name: install packages
    become: true
    become_user: root
    dnf:
      state: present
      name:
       - mariadb-server
       - python3-PyMySQL
  - name: Start mariadb
    ansible.builtin.systemd:
      name: mariadb.service
      enabled: yes
      state: started
  - name: Create a new database 
    community.mysql.mysql_db:
      name: slurm_acct_db
      state: present
  - name: Create database user with password and all database privileges and 'WITH GRANT OPTION'
    community.mysql.mysql_user:
      name: slurm
      password: S3cur3P4ss
      priv: '*.*:ALL,GRANT'
      state: present
  - name: Start slurmdb
    ansible.builtin.systemd:
      name: slurmdbd.service
      enabled: yes
      state: started
  - name: Restart slurmctld
    ansible.builtin.systemd:
      name: slurmctld.service
      enabled: yes
      state: restarted
