---
- name: Configure Compute Node
  hosts: "*compute*,*gpu*"
  gather_facts: yes
  tasks:
  - name: Create /scratch
    ansible.builtin.file:
      path: /scratch
      state: directory
      owner: root
      group: root
      mode: '0751'
  - debug:
      msg: Disk sdb does not exist.
    when: ansible_devices.sdb is undefined
    ignore_errors: yes  
  - name: Create an xfs filesystem on /dev/sdb
    filesystem:
      fstype: xfs
      dev: /dev/sdb
    when: ansible_devices.sdb is defined
    ignore_errors: yes
  - name: Fetch the UUID of /dev/sdb
    command: blkid -s UUID -o value /dev/sdb
    changed_when: false
    register: blkid_out
    when: ansible_devices.sdb is defined
    ignore_errors: yes
  - name: Mount /dev/sdb by UUID
    ansible.posix.mount:
      path: /scratch
      src: UUID={{ blkid_out.stdout }}
      fstype: xfs
      opts: defaults
      state: mounted
    when: ansible_devices.sdb is defined
    ignore_errors: yes
  - name: Update auto.misc file to mount /opt
    become: true
    blockinfile:
      dest: /etc/auto.misc
      content: "/opt    -fstype=nfs     192.168.200.251:/opt"
      state: present     
  - name: Restart autofs
    ansible.builtin.service:
      name: autofs
      state: restarted
      enabled: yes
  - name: Read /opt/id_rsa.pub
    shell: cat /opt/id_rsa.pub
    register: sshkey
  - name: Add key to authorized_keys
    ansible.posix.authorized_key:
      user: root
      state: present
      key: "{{ sshkey.stdout }}"
  - name: Copy ssh private key from /opt
    ansible.builtin.copy:
      src: /opt/id_rsa
      dest: /root/.ssh/id_rsa
      remote_src: yes


