---
- name: Configure Login Node
  hosts: "*login*"
  gather_facts: no
  tasks:
  - name: Export /opt
    template:
      src: exports.j2
      dest: /etc/exports
      owner: root
      group: root
      mode: 0644
  - name: enable nfs-server
    service:
      name: nfs-server
      state: restarted
      enabled: yes
  - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
    community.crypto.openssh_keypair:
      path: /root/.ssh/id_rsa
      regenerate: partial_idempotence
  - name: Copy ssh public key to /opt
    ansible.builtin.copy:
      src: /root/.ssh/id_rsa.pub
      dest: /opt/id_rsa.pub
      remote_src: yes
  - name: Copy ssh private key to /opt
    ansible.builtin.copy:
      src: /root/.ssh/id_rsa
      dest: /opt/id_rsa
      remote_src: yes
