---
- name: Configure local repositories
  hosts: all
  gather_facts: yes
  tasks:
#   Clean up /etc/yum.repos.d directory
  - name: Find files to clean up /etc/yum.repos.d directory
    find:
      paths: /etc/yum.repos.d
      file_type: file
      excludes:
        - "ansible-managed.repo"
    register: yum_repos_cleanup
  - name: Delete files to clean up /etc/yum.repos.d directory
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ yum_repos_cleanup['files'] }}"
#   Add all the repos to ansible-managed.repo file so its all in one file
  - name: Add Rocky Linux 8 Base repo
    yum_repository:
      name: Rocky-Linux-8-BaseOS
      file: ansible-managed
      description: Rocky Linux 8 BaseOS
      baseurl: http://repo.r-hpc.com/repo/rocky-baseos-8
      enabled: yes
      gpgcheck: yes
      gpgkey: http://repo.r-hpc.com/repo/rocky-baseos-8/RPM-GPG-KEY-Rocky-8
    when:
      - ansible_facts['distribution'] == "Rocky"
      - ansible_facts['distribution_major_version'] == "8"
  - name: Import Rocky Linux 8 key
    ansible.builtin.rpm_key:
      state: present
      key: http://repo.r-hpc.com/repo/rocky-baseos-8/RPM-GPG-KEY-Rocky-8
  - name: Add Rocky Linux 8 Extras repo
    yum_repository:
      name: Rocky-Linux-8-Extras
      file: ansible-managed
      description: Rocky Linux 8 Extras
      baseurl: http://repo.r-hpc.com/repo/rocky-extras-8
      enabled: yes
      gpgcheck: yes
      gpgkey: http://repo.r-hpc.com/repo/rocky-baseos-8/RPM-GPG-KEY-Rocky-8
    when:
      - ansible_facts['distribution'] == "Rocky"
      - ansible_facts['distribution_major_version'] == "8"
  - name: Add Rocky Linux 8 AppStream repo
    yum_repository:
      name: Rocky-Linux-8-AppStream
      file: ansible-managed
      description: Rocky Linux 8 AppStream
      baseurl: http://repo.r-hpc.com/repo/rocky-appstream-8
      enabled: yes
      gpgcheck: yes
      gpgkey: http://repo.r-hpc.com/repo/rocky-baseos-8/RPM-GPG-KEY-Rocky-8
    when:
      - ansible_facts['distribution'] == "Rocky"
      - ansible_facts['distribution_major_version'] == "8"
  - name: Add Rocky Linux 8 PowerTools repo
    yum_repository:
      name: Rocky-Linux-8-PowerTools
      file: ansible-managed
      description: Rocky Linux 8 PowerTools
      baseurl: http://repo.r-hpc.com/repo/rocky-powertools-8
      enabled: yes
      gpgcheck: yes
      gpgkey: http://repo.r-hpc.com/repo/rocky-baseos-8/RPM-GPG-KEY-Rocky-8
    when:
      - ansible_facts['distribution'] == "Rocky"
      - ansible_facts['distribution_major_version'] == "8"
  - name: Add Oracle Linux 8.6 BaseOS repo
    yum_repository:
      name: Oracle-Linux-8.6-BaseOS
      file: ansible-managed
      description: Oracle Linux 8.6 BaseOS
      baseurl: http://repo.r-hpc.com/repo/ol8_u6_baseos_base
      enabled: yes
      gpgcheck: yes
      gpgkey: http://repo.r-hpc.com/repo/ol8_baseos_latest/RPM-GPG-KEY-oracle-ol8
    when:
      - ansible_facts['distribution'] == "OracleLinux"
      - ansible_facts['distribution_version'] == "8.6"
  - name: Add Oracle Linux 8.7 BaseOS repo
    yum_repository:
      name: Oracle-Linux-8.7-BaseOS
      file: ansible-managed
      description: Oracle Linux 8.7 BaseOS
      baseurl: http://repo.r-hpc.com/repo/ol8_u7_baseos_base
      enabled: yes
      gpgcheck: yes
      gpgkey: http://repo.r-hpc.com/repo/ol8_baseos_latest/RPM-GPG-KEY-oracle-ol8
    when:
      - ansible_facts['distribution'] == "OracleLinux"
      - ansible_facts['distribution_version'] == "8.7"
  - name: Import Oracle Linux 8 key
    ansible.builtin.rpm_key:
      state: present
      key: http://repo.r-hpc.com/repo/ol8_baseos_latest/RPM-GPG-KEY-oracle-ol8
  - name: Add Oracle Linux 8 BaseOS Latest repo
    yum_repository:
      name: Oracle-Linux-8-BaseOS-Latest
      file: ansible-managed
      description: Oracle Linux 8 BaseOS Latest
      baseurl: http://repo.r-hpc.com/repo/ol8_baseos_latest
      enabled: yes
      gpgcheck: yes
      gpgkey: http://repo.r-hpc.com/repo/ol8_baseos_latest/RPM-GPG-KEY-oracle-ol8
    when:
      - ansible_facts['distribution'] == "OracleLinux"
      - ansible_facts['distribution_major_version'] == "8"
  - name: Add Oracle Linux 8 Unbreakable 8.6 repo
    yum_repository:
      name: Oracle-Linux-8R6-UEK
      file: ansible-managed
      description: Oracle Linux 8 UEK R6
      baseurl: http://repo.r-hpc.com/repo/ol8_UEKR6
      enabled: yes
      gpgcheck: yes
      gpgkey: http://repo.r-hpc.com/repo/ol8_baseos_latest/RPM-GPG-KEY-oracle-ol8
    when:
      - ansible_facts['distribution'] == "OracleLinux"
      - ansible_facts['distribution_version'] == "8.6"
  - name: Add Oracle Linux 8 Unbreakable 8.7 repo
    yum_repository:
      name: Oracle-Linux-8R7-UEK
      file: ansible-managed
      description: Oracle Linux 8 UEK R7
      baseurl: http://repo.r-hpc.com/repo/ol8_UEKR7
      enabled: yes
      gpgcheck: yes
      gpgkey: http://repo.r-hpc.com/repo/ol8_baseos_latest/RPM-GPG-KEY-oracle-ol8
    when:
      - ansible_facts['distribution'] == "OracleLinux"
      - ansible_facts['distribution_version'] == "8.7"
  - name: Add Oracle Linux 8 Unbreakable 8.6 RDMA repo
    yum_repository:
      name: Oracle-Linux-8R6-UEK-RDMA
      file: ansible-managed
      description: Oracle Linux 8 UEK R6 RDMA
      baseurl: http://repo.r-hpc.com/repo/ol8_UEKR6_RDMA
      enabled: no
      gpgcheck: yes
      gpgkey: http://repo.r-hpc.com/repo/ol8_baseos_latest/RPM-GPG-KEY-oracle-ol8
    when:
      - ansible_facts['distribution'] == "OracleLinux"
      - ansible_facts['distribution_version'] == "8.6"
  - name: Add Oracle Linux 8 Unbreakable 8.7 RDMA repo
    yum_repository:
      name: Oracle-Linux-8R7-UEK-RDMA
      file: ansible-managed
      description: Oracle Linux 8 UEK R7 RDMA
      baseurl: http://repo.r-hpc.com/repo/ol8_UEKR7_RDMA
      enabled: no
      gpgcheck: yes
      gpgkey: http://repo.r-hpc.com/repo/ol8_baseos_latest/RPM-GPG-KEY-oracle-ol8
    when:
      - ansible_facts['distribution'] == "OracleLinux"
      - ansible_facts['distribution_version'] == "8.7"
  - name: Add Oracle Linux 8 AppStream repo
    yum_repository:
      name: Oracle-Linux-8-AppStream
      file: ansible-managed
      description: Oracle Linux 8 AppStream
      baseurl: http://repo.r-hpc.com/repo/ol8_appstream
      enabled: yes
      gpgcheck: yes
      gpgkey: http://repo.r-hpc.com/repo/ol8_baseos_latest/RPM-GPG-KEY-oracle-ol8
    when:
      - ansible_facts['distribution'] == "OracleLinux"
      - ansible_facts['distribution_major_version'] == "8"
  - name: Add Oracle Linux 8 Addons repo
    yum_repository:
      name: Oracle-Linux-8-Addons
      file: ansible-managed
      description: Oracle Linux 8 Addon
      baseurl: http://repo.r-hpc.com/repo/ol8_addons
      enabled: yes
      gpgcheck: yes
      gpgkey: http://repo.r-hpc.com/repo/ol8_baseos_latest/RPM-GPG-KEY-oracle-ol8
    when:
      - ansible_facts['distribution'] == "OracleLinux"
      - ansible_facts['distribution_major_version'] == "8"
  - name: Add Oracle Linux 8 EPEL repo
    yum_repository:
      name: Oracle-Linux-8-EPEL
      file: ansible-managed
      description: Oracle Linux 8 EPEL
      baseurl: http://repo.r-hpc.com/repo/ol8_developer_EPEL
      enabled: yes
      gpgcheck: yes
      gpgkey: http://repo.r-hpc.com/repo/ol8_baseos_latest/RPM-GPG-KEY-oracle-ol8
    when:
      - ansible_facts['distribution'] == "OracleLinux"
      - ansible_facts['distribution_major_version'] == "8"
  - name: Add Intel OneAPI repo
    yum_repository:
      name: oneAPI
      file: ansible-managed
      description: Intel(R) oneAPI repository
      baseurl: http://repo.r-hpc.com/repo/oneAPI
      enabled: yes
      gpgcheck: yes
      gpgkey: http://repo.r-hpc.com/repo/oneAPI/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
  - name: Import Intel oneAPI key
    ansible.builtin.rpm_key:
      state: present
      key: http://repo.r-hpc.com/repo/oneAPI/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
  - name: Add openHPC Base repo
    yum_repository:
      name: OpenHPC
      file: ansible-managed
      description: OpenHPC-2 - Base
      baseurl: http://repo.r-hpc.com/repo/OpenHPC
      enabled: yes
      gpgcheck: yes
      gpgkey: http://repo.r-hpc.com/repo/OpenHPC/RPM-GPG-KEY-OpenHPC-2
    when:
      - ansible_facts['os_family'] in ['RedHat', 'Rocky']
      - ansible_facts['distribution_major_version'] == "8"
  - name: Import OpenHPC key
    ansible.builtin.rpm_key:
      state: present
      key: http://repo.r-hpc.com/repo/OpenHPC/RPM-GPG-KEY-OpenHPC-2
  - name: Add openHPC Updates repo
    yum_repository:
      name: OpenHPC-updates
      file: ansible-managed
      description: OpenHPC-2 - Updates
      baseurl: http://repo.r-hpc.com/repo/OpenHPC-updates
      enabled: yes
      gpgcheck: yes
      gpgkey: http://repo.r-hpc.com/repo/OpenHPC/RPM-GPG-KEY-OpenHPC-2
    when:
      - ansible_facts['os_family'] in ['RedHat', 'Rocky']
      - ansible_facts['distribution_major_version'] == "8"
  - name: Add Dell srvadmin repo
    yum_repository:
      name: srvadmin
      file: ansible-managed
      description: Dell srvadmin
      baseurl: http://repo.r-hpc.com/repo/dell-system-update_dependent
      enabled: yes
      gpgcheck: no
    when:
      - ansible_facts['os_family'] in ['RedHat', 'Rocky']
      - ansible_facts['virtualization_role'] != "guest"
  - name: Add EPEL repo
    yum_repository:
      name: epel
      file: ansible-managed
      description: EPEL
      baseurl: http://repo.r-hpc.com/repo/epel
      enabled: yes
      gpgkey: http://repo.r-hpc.com/repo/epel/RPM-GPG-KEY-EPEL-8
      gpgcheck: yes
    when:
      - ansible_facts['os_family'] in ['RedHat', 'Rocky']
      # Oracle Linux 8 has its own EPEL
      - ansible_facts['distribution'] != "OracleLinux"
      - ansible_facts['distribution_major_version'] == "8"
  - name: Import EPEL key
    ansible.builtin.rpm_key:
      state: present
      key: http://repo.r-hpc.com/repo/epel/RPM-GPG-KEY-EPEL-8
  - name: Add EPEL modular repo
    yum_repository:
      name: epel-modular
      file: ansible-managed
      description: EPEL modular
      baseurl: http://repo.r-hpc.com/repo/epel-modular
      enabled: yes
      gpgkey: http://repo.r-hpc.com/repo/epel/RPM-GPG-KEY-EPEL-8
      gpgcheck: yes
    when:
      - ansible_facts['os_family'] in ['RedHat', 'Rocky']
      # Oracle Linux 8 has its own EPEL
      - ansible_facts['distribution'] != "OracleLinux"
      - ansible_facts['distribution_major_version'] == "8"
  - name: Add REMI repo
    yum_repository:
      name: remi
      file: ansible-managed
      description: REMI
      baseurl: http://repo.r-hpc.com/repo/remi
      enabled: no
      gpgkey: http://repo.r-hpc.com/repo/remi/RPM-GPG-KEY-remi.el8
      gpgcheck: yes
    when:
      - ansible_facts['os_family'] in ['RedHat', 'Rocky']
      - ansible_facts['distribution_major_version'] == "8"
  - name: Import REMI key
    ansible.builtin.rpm_key:
      state: present
      key: http://repo.r-hpc.com/repo/remi/RPM-GPG-KEY-remi.el8
  - name: Add REMI modular repo
    yum_repository:
      name: remi-modular
      file: ansible-managed
      description: REMI modular
      baseurl: http://repo.r-hpc.com/repo/remi-modular
      enabled: no
      gpgkey: http://repo.r-hpc.com/repo/remi/RPM-GPG-KEY-remi.el8
      gpgcheck: yes
    when:
      - ansible_facts['os_family'] in ['RedHat', 'Rocky']
      - ansible_facts['distribution_major_version'] == "8"
  - name: Add CUDA RHEL8 repo
    yum_repository:
      name: cuda-rhel8
      file: ansible-managed
      description: CUDA RHEL8
      baseurl: http://repo.r-hpc.com/repo/cuda-rhel8-x86_64
      enabled: yes
      gpgcheck: yes
      gpgkey: http://repo.r-hpc.com/repo/cuda-rhel8-x86_64/D42D0685.pub
    when:
      - ansible_facts['os_family'] in ['RedHat', 'Rocky']
      - ansible_facts['distribution_major_version'] == "8"
  - name: Import NVIDIA key
    ansible.builtin.rpm_key:
      state: present
      key: http://repo.r-hpc.com/repo/cuda-rhel8-x86_64/D42D0685.pub
  - name: Add CUDA RHEL8 SBSA repo
    yum_repository:
      name: cuda-rhel8-sbsa
      file: ansible-managed
      description: CUDA RHEL8 SBSA
      baseurl: http://repo.r-hpc.com/repo/cuda-rhel8-cross-linux-sbsa
      enabled: yes
      gpgcheck: yes
      gpgkey: http://repo.r-hpc.com/repo/cuda-rhel8-x86_64/D42D0685.pub
    when:
      - ansible_facts['os_family'] in ['RedHat', 'Rocky']
      - ansible_facts['distribution_major_version'] == "8"
  - name: Add Mellanox OFED repo
    yum_repository:
      name: ofed-5.7-1.0.2.0
      file: ansible-managed
      description: Mellanox OFED 5.7.1-1.0.2.0
      baseurl: http://repo.r-hpc.com/repo/ofed/MLNX_OFED_LINUX-5.7-1.0.2.0-rhel8.6-x86_64/RPMS
      enabled: yes
      gpgcheck: yes
      gpgkey: http://repo.r-hpc.com/repo/ofed/RPM-GPG-KEY-Mellanox
    when:
      - ansible_facts['os_family'] in ['RedHat', 'Rocky']
      - ansible_facts['distribution_major_version'] == "8"
  - name: Import Mellanox key
    ansible.builtin.rpm_key:
      state: present
      key: http://repo.r-hpc.com/repo/ofed/RPM-GPG-KEY-Mellanox
  - name: Add Teleport repo
    yum_repository:
      name: teleport
      file: ansible-managed
      description: Teleport
      baseurl: http://repo.r-hpc.com/repo/teleport
      enabled: yes
      gpgcheck: yes
      gpgkey: http://repo.r-hpc.com/repo/teleport/RPM-GPG-KEY-teleport
    when:
      - ansible_facts['os_family'] in ['RedHat', 'Rocky']
      - ansible_facts['distribution_major_version'] == "8"
  - name: Import Teleport key
    ansible.builtin.rpm_key:
      state: present
      key: http://repo.r-hpc.com/repo/teleport/RPM-GPG-KEY-teleport
